apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devicedatahub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "devicedatahub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  MQTT_USERNAME: {{ .Values.mqtt.username | quote }}
  MQTT_PASSWORD: {{ .Values.mqtt.password | quote }}
